// Generated by scripts/prepare-bundled-runtime.py.
import Foundation

enum BundledRuntimeFiles {
    static let hashes: [String: String] = [
        "libgmp.10.dylib": "2a1dbf5a7bef70890a45937c001c959461e04839abc49990f8793d1b5eb1664f",
        "libgnutls.30.dylib": "bf16ef512dc7d45502e493f2a32ef28757d8524923e28e9490cfddb428e82f8f",
        "libhogweed.7.0.dylib": "5a1259c6c69ebef010033c32eb6f0c433ac030e2c7eeb54f08ea9f97109020e7",
        "libidn2.0.dylib": "8dbead371c622cf6d9dd9c451f2f5a07c7f98267bea7e219806a9734b4a77599",
        "libnettle.9.0.dylib": "5327481c2ff90089d5c2e89fc3086ae5ca7c3769d69c78b3bef4200fd8434f03",
        "libopenconnect.5.dylib": "8d6b5a420d1346a2052805b64ea3fd169dc1957cef20100a6531724e81608ffb",
        "libp11-kit.0.dylib": "094b80ae42bf6f64dd7fbb826d17b56705e320bb05b7999abad514e4cc9ec3e4",
        "libstoken.1.dylib": "29364e6d74acec34a03e135b5c40e8e3d39a7dedda63424b6833bd48a0a20d74",
        "libtasn1.6.dylib": "323618ec0d8c82d733efc06d783971b1eeea534826cbb249b9fabdbbb0bf68ee",
        "libtomcrypt.1.dylib": "5a95e7cac606e868011f16d1aca6a43c2b976473b6aa6c1df9a65ab19af56d08",
        "libtommath.1.dylib": "3918818f11e420e5728565abd00fa97a197aafa2e9d36cb56bacf41b68ffcfb5",
        "libunistring.5.dylib": "cecfb53a1f691d9d7cd0487cf8a699fe3e2a9da1e34009fce73f3d23ef37c84f",
        "openconnect": "944541e14b124792d6836730a7027f449a6c4bb9d157b1e7408f80ccec323027",
        "vpnc-script--no-dns": "2fa3937eaa9fbccd964ed2c47bd70a6dc99f2dba6289e122bc884edd4e992fa6",
    ]
    static let architectures = ["arm64"]
    static let minimumOS = OperatingSystemVersion(majorVersion: 13, minorVersion: 0, patchVersion: 0)
}
