import Foundation

enum DependencyInstallError: Error, LocalizedError {
    case userCancelled
    case unsupported(reason: String)
    case configIO(underlying: Error)

    var errorDescription: String? {
        switch self {
        case .userCancelled: return "Authorization cancelled."
        case .unsupported(let reason): return reason
        case .configIO: return "The configuration could not be updated. Check Settings and local storage permissions."
        }
    }
}

enum DependencyInstaller {
    static func sudoersFilenameComponent(for username: String) -> String {
        String(username.map {
            ($0.isASCII && ($0.isLetter || $0.isNumber)) || $0 == "-" || $0 == "_" ? $0 : "_"
        })
    }

    static func legacySudoersPaths(username: String) -> [String] {
        var names = [sudoersFilenameComponent(for: username)]
        if !username.isEmpty && username.allSatisfy({ $0.isASCII && ($0.isLetter || $0.isNumber || "._-".contains($0)) }) {
            names.append(username)
        }
        return Array(Set(names)).sorted().map { "/etc/sudoers.d/vpnmenubar-" + $0 }
    }

    static func removeLegacySudoers(username: String) async throws {
        _ = try await Task.detached { try PrivilegedCommand.run(legacyRemovalCommand(username: username)) }.value
    }

    static func legacyRemovalCommand(username: String) -> String {
        let paths = legacySudoersPaths(username: username)
        return "set -eu\n" + paths.map { path in
            let q = PrivilegedCommand.quote(path)
            // Recheck ownership and provenance after authorization; never remove hand-written rules.
            return """
            if [ -e \(q) ] || [ -L \(q) ]; then
                [ ! -L \(q) ] && [ -f \(q) ] || exit 51
                [ "$(/usr/bin/stat -f %u \(q))" = 0 ] || exit 52
                /usr/bin/grep -Eq '^# (Auto-generated by VPNMenuBar|Generated by VPNMenuBar|Managed by VPNMenuBar)' \(q) || exit 53
                /bin/rm \(q)
            fi
            """
        }.joined(separator: "\n") + "\n/usr/sbin/visudo -c >/dev/null"
    }

    static func resetManagedRuntime(store: ConfigStore) throws {
        guard var config = try store.load() else { return }
        config.openconnectPath = ManagedRuntime.openconnect
        config.vpncScriptPath = ManagedRuntime.script
        config.skipDNSModification = true
        try store.save(config)
    }
}
