import Foundation
import AppKit

enum DependencyInstallError: Error, LocalizedError {
    case userCancelled
    case shellFailed(stderr: String)
    case osascriptFailed(message: String)
    case unsupported(reason: String)
    case configIO(underlying: Error)

    var errorDescription: String? {
        switch self {
        case .userCancelled:
            return "Cancelled."
        case .shellFailed(let s):
            return s.isEmpty ? "Shell command failed." : s
        case .osascriptFailed(let m):
            return m
        case .unsupported(let r):
            return r
        case .configIO(let e):
            return "Config I/O failed: \(e.localizedDescription)"
        }
    }
}

/// Stateless namespace exposing the four fix actions surfaced by
/// `InAppFix`. UI views invoke these from a dispatcher tied to a
/// `runningFix` state and an error alert.
enum DependencyInstaller {

    /// Open Terminal.app and pre-type the official Homebrew installer
    /// command. Returns immediately. The user runs the command in
    /// Terminal and comes back to click Recheck.
    static func openTerminalForHomebrew() throws {
        let installerCmd = "NONINTERACTIVE=1 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
        let escaped = appleScriptEscape(installerCmd)
        let source = """
        tell application "Terminal"
            activate
            do script "\(escaped)"
        end tell
        """
        try runAppleScript(source)
    }

    /// Run `brew install openconnect` as the current user via Process.
    /// Streams stdout+stderr lines to the progress callback.
    /// Throws `shellFailed(stderr:)` on non-zero exit.
    static func installOpenconnect(
        brewPath: String,
        progress: @Sendable @escaping (String) -> Void
    ) async throws {
        try await Task.detached(priority: .userInitiated) {
            let p = Process()
            p.executableURL = URL(fileURLWithPath: brewPath)
            p.arguments = ["install", "openconnect"]

            // brew needs its own bin dir on PATH so it can find auxiliary tools.
            let brewDir = (brewPath as NSString).deletingLastPathComponent
            var env = ProcessInfo.processInfo.environment
            env["PATH"] = "\(brewDir):/usr/bin:/bin:/usr/sbin:/sbin"
            env["HOMEBREW_NO_AUTO_UPDATE"] = "1"
            p.environment = env

            let outPipe = Pipe()
            let errPipe = Pipe()
            p.standardOutput = outPipe
            p.standardError = errPipe
            p.standardInput = FileHandle.nullDevice

            // Accumulate stderr for the failure tail; also forward live lines to UI.
            let stderrAccum = StderrAccumulator()

            outPipe.fileHandleForReading.readabilityHandler = { handle in
                let chunk = handle.availableData
                if chunk.isEmpty {
                    handle.readabilityHandler = nil
                    return
                }
                if let s = String(data: chunk, encoding: .utf8) {
                    for line in s.split(separator: "\n") where !line.trimmingCharacters(in: .whitespaces).isEmpty {
                        progress(String(line))
                    }
                }
            }
            errPipe.fileHandleForReading.readabilityHandler = { handle in
                let chunk = handle.availableData
                if chunk.isEmpty {
                    handle.readabilityHandler = nil
                    return
                }
                stderrAccum.append(chunk)
                if let s = String(data: chunk, encoding: .utf8) {
                    for line in s.split(separator: "\n") where !line.trimmingCharacters(in: .whitespaces).isEmpty {
                        progress(String(line))
                    }
                }
            }

            try p.run()
            p.waitUntilExit()
            outPipe.fileHandleForReading.readabilityHandler = nil
            errPipe.fileHandleForReading.readabilityHandler = nil

            if p.terminationStatus != 0 {
                let stderrText = stderrAccum.snapshotString()
                let tail = String(stderrText.suffix(400))
                throw DependencyInstallError.shellFailed(
                    stderr: tail.isEmpty ? "brew install exited \(p.terminationStatus)" : tail
                )
            }
        }.value
    }

    /// Write /etc/sudoers.d/vpnmenubar-<user> via osascript admin (one TouchID).
    /// Validates with visudo before installing.
    static func installSudoersRule(
        username: String,
        openconnectPath: String
    ) async throws {
        try await Task.detached(priority: .userInitiated) {
            // 1. Build content
            let content = """
            # Auto-generated by VPNMenuBar at \(Date())
            # Grants \(username) passwordless sudo for openconnect, pkill, and route.
            # Remove this file to revoke: sudo rm /etc/sudoers.d/vpnmenubar-\(username)
            \(username) ALL=(root) NOPASSWD: \(openconnectPath), /usr/bin/pkill -x openconnect, /sbin/route
            """

            // 2. Write to a user-owned temp file
            let tmp = NSTemporaryDirectory() + "vpnmenubar-sudoers-\(UUID().uuidString)"
            try content.write(toFile: tmp, atomically: true, encoding: .utf8)
            defer { try? FileManager.default.removeItem(atPath: tmp) }

            // 3. Build privileged shell command
            let dest = "/etc/sudoers.d/vpnmenubar-\(username)"
            let shellCmd = "/usr/sbin/visudo -c -f \"\(tmp)\" && /usr/bin/install -m 440 -o root -g wheel \"\(tmp)\" \"\(dest)\""

            // 4. Wrap in AppleScript with admin privileges (one TouchID)
            let asEscaped = appleScriptEscape(shellCmd)
            let source = """
            do shell script "\(asEscaped)" with administrator privileges
            """
            try runAppleScript(source)
        }.value
    }

    /// Reset the vpncScriptPath in saved config to the architecture-correct
    /// default. No privilege escalation needed — just a config write.
    static func resetVpncScriptPath(to newPath: String, store: ConfigStore) throws {
        do {
            guard var config = try store.load() else {
                throw DependencyInstallError.unsupported(
                    reason: "No config to update yet — finish Onboarding first."
                )
            }
            config.vpncScriptPath = newPath
            try store.save(config)
        } catch let e as DependencyInstallError {
            throw e
        } catch {
            throw DependencyInstallError.configIO(underlying: error)
        }
    }

    // MARK: - helpers

    private static func appleScriptEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
         .replacingOccurrences(of: "\"", with: "\\\"")
    }

    /// Execute an AppleScript source string. Maps the well-known cancel
    /// code (-128) to `userCancelled`; everything else to `osascriptFailed`.
    private static func runAppleScript(_ source: String) throws {
        var errorInfo: NSDictionary?
        guard let script = NSAppleScript(source: source) else {
            throw DependencyInstallError.osascriptFailed(message: "Could not build AppleScript")
        }
        _ = script.executeAndReturnError(&errorInfo)
        if let info = errorInfo {
            let code = (info[NSAppleScript.errorNumber] as? Int) ?? 0
            if code == -128 {
                throw DependencyInstallError.userCancelled
            }
            let msg = (info[NSAppleScript.errorMessage] as? String) ?? "unknown AppleScript error"
            throw DependencyInstallError.osascriptFailed(message: "\(msg) (code \(code))")
        }
    }
}

/// Tiny mutex-protected wrapper so the Pipe readabilityHandler thread can
/// append to the stderr accumulator without racing the consumer thread.
private final class StderrAccumulator: @unchecked Sendable {
    private let lock = NSLock()
    private var data = Data()

    func append(_ chunk: Data) {
        lock.lock(); defer { lock.unlock() }
        data.append(chunk)
    }

    func snapshotString() -> String {
        lock.lock(); defer { lock.unlock() }
        return String(data: data, encoding: .utf8) ?? ""
    }
}
