#!/bin/bash
# Offline audit / explicit revocation only. No network install or sudoers grants.
set -euo pipefail

if [[ "${1:-}" == '--remove-legacy-sudoers' ]]; then
    [[ $EUID -eq 0 ]] || { echo 'Run this removal mode as an administrator, supplying the affected login name.' >&2; exit 1; }
    TARGET_USER=${2:?Supply the affected login name}
    [[ "$TARGET_USER" =~ ^[A-Za-z0-9._-]+$ ]] || { echo 'Invalid login name' >&2; exit 1; }
    SAFE_USER=${TARGET_USER//[^A-Za-z0-9_-]/_}
    for NAME in "$SAFE_USER" "$TARGET_USER"; do
        RULE="/etc/sudoers.d/vpnmenubar-$NAME"
        if [[ -e "$RULE" || -L "$RULE" ]]; then
            [[ -f "$RULE" && ! -L "$RULE" && "$(/usr/bin/stat -f %u "$RULE")" == 0 ]] || exit 2
            /usr/bin/grep -Eq '^# (Auto-generated by VPNMenuBar|Generated by VPNMenuBar|Managed by VPNMenuBar)' "$RULE" || {
                echo 'Refusing to remove an unrecognized rule; ask IT to review it.' >&2; exit 3;
            }
            /bin/rm "$RULE"
        fi
    done
    /usr/sbin/visudo -c
    exit
fi
[[ $# -eq 0 ]] || { echo 'Usage: bash install-deps.sh [--remove-legacy-sudoers LOGIN]' >&2; exit 1; }
echo 'OpenConnect is bundled with VPNMenuBar. No system dependency installation is needed.'
echo 'The app verifies bundled file hashes before each connection.'
