"""Run generated commands in temporary directories; never authorize or alter system policy."""
import os
import pathlib
import subprocess
import sys
import shutil

root = pathlib.Path(sys.argv[1])
uid = str(os.getuid())

def run(command):
    return subprocess.run(['/bin/sh', '-c', command], capture_output=True, text=True, timeout=10)

# Exercise bundled byte validation and the exact snapshot staging commands.
import shlex
source = pathlib.Path('VPNMenuBar/Resources/BundledRuntime').resolve()
runtime = root / 'Runtime with spaces'
shutil.copytree(source, runtime)
audit = (root/'validate.sh').read_text().replace(str(source), str(runtime))
assert run(audit).returncode == 0
entry = runtime/'openconnect'
entry.write_bytes(entry.read_bytes() + b'changed')
assert run(audit).returncode != 0, 'tampered binary accepted'
shutil.copyfile(source/'openconnect', entry)
entry.chmod(0o644)
assert run(audit).returncode != 0, 'nonexecutable entry accepted'
entry.unlink(); entry.symlink_to(source/'openconnect')
assert run(audit).returncode != 0, 'symlink entry accepted'
entry.unlink(); shutil.copy2(source/'openconnect', entry)
assert run(audit).returncode == 0
stage = (root/'stage.sh').read_text().replace(str(source), str(runtime))
session = root/'snapshot'
session.mkdir(mode=0o700)
result = run('set -eu\nsession=' + shlex.quote(str(session)) + '\n' + stage)
assert result.returncode == 0, result.stderr
assert (session/'runtime').stat().st_mode & 0o777 == 0o700
assert (session/'runtime/openconnect').stat().st_mode & 0o777 == 0o500
# Running after relocation proves no fixed system-install directory is needed.
result = subprocess.run([str(session/'runtime/openconnect'), '--version'], capture_output=True, timeout=10)
assert result.returncode == 0, result.stderr
entry.write_bytes(entry.read_bytes() + b'tampered after packaging')
assert (session/'runtime/openconnect').read_bytes() == (source/'openconnect').read_bytes()
shutil.rmtree(session/'runtime')
result = run('set -eu\nsession=' + shlex.quote(str(session)) + '\n' + stage)
assert result.returncode != 0, 'changed source accepted during privileged snapshot'
print('PASS: bundled hashes, permissions, symlink rejection, isolated snapshot and relocated execution')

resolver = root / 'resolver'
dns = (root / 'dns.sh').read_text().replace('/etc/resolver', str(resolver))
dns = dns.replace('" = 0 ]', '" = ' + uid + ' ]')
dns = dns.replace('/usr/sbin/chown root:wheel "$tmp"', ':')
dns = dns.replace('/usr/bin/killall -HUP mDNSResponder', '/usr/bin/true')
target = resolver / 'intranet.example.com'
assert run(dns).returncode == 0
assert resolver.stat().st_mode & 0o777 == 0o755
assert target.stat().st_mode & 0o777 == 0o644
assert 'nameserver 10.0.0.53\n' in target.read_text()
assert run(dns).returncode == 0, 'managed resolver replacement failed'
target.write_text('unmanaged fixture\n')
assert run(dns).returncode != 0
assert target.read_text() == 'unmanaged fixture\n'
target.unlink()
victim = root / 'untouched'
victim.write_text('fixture\n')
target.symlink_to(victim)
assert run(dns).returncode != 0 and victim.read_text() == 'fixture\n'
target.unlink()
resolver.chmod(0o777)
assert run(dns).returncode != 0, 'writable directory accepted'
resolver.chmod(0o755)
assert not list(resolver.glob('.vpnmenubar.*'))
print('PASS: resolver creation/replacement, modes, unmanaged/symlink/writable-directory rejection')

sudoers = root / 'sudoers.d'
sudoers.mkdir()
revoke = (root / 'revoke.sh').read_text().replace('/etc/sudoers.d', str(sudoers))
revoke = revoke.replace('" = 0 ]', '" = ' + uid + ' ]')
revoke = revoke.replace('/usr/sbin/visudo -c', '/usr/bin/true')
rule = sudoers / 'vpnmenubar-first.last'
rule.write_text('# Generated by VPNMenuBar\nfixture\n')
assert run(revoke).returncode == 0 and not rule.exists()
rule.write_text('# Manually managed fixture\n')
assert run(revoke).returncode != 0 and rule.exists()
rule.unlink()
rule.symlink_to(victim)
assert run(revoke).returncode != 0 and victim.read_text() == 'fixture\n'
print('PASS: recognized legacy rule removal and unmanaged/symlink rejection')

# Verify actual bundled libraries, not only command-string expectations.
import ctypes
os.environ['GNUTLS_SYSTEM_PRIORITY_FILE'] = '/dev/null'
os.environ['P11_KIT_NO_USER_CONFIG'] = '1'
gnutls = ctypes.CDLL(str(source/'libgnutls.30.dylib'))
gnutls.gnutls_get_system_config_file.restype = ctypes.c_char_p
assert gnutls.gnutls_get_system_config_file() == b'/dev/null'
p11 = ctypes.CDLL(str(source/'libp11-kit.0.dylib'))
p11.p11_kit_modules_load.argtypes = [ctypes.c_int]
p11.p11_kit_modules_load.restype = ctypes.POINTER(ctypes.c_void_p)
modules = p11.p11_kit_modules_load(0)
assert modules and not modules[0], 'Bundled p11-kit loaded an external module'
p11.p11_kit_modules_release.argtypes = [ctypes.POINTER(ctypes.c_void_p)]
p11.p11_kit_modules_release(modules)
print('PASS: actual GnuTLS configuration and p11-kit module isolation')
