#!/usr/bin/env python3
"""Package local build dependencies; never downloads or installs software."""
import hashlib, json, os, pathlib, re, shutil, subprocess, tempfile, importlib.util
root = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location('runtime_package', root/'scripts/runtime-package.py')
runtime_package = importlib.util.module_from_spec(spec); spec.loader.exec_module(runtime_package)
isolated_p11 = (root/'build/p11-isolated/compiled/p11-kit/libp11-kit.0.dylib').resolve(strict=True)
build = root/'build'; build.mkdir(exist_ok=True)
lock = build/'runtime-packaging.lock'
# Never overwrite a lock from another process or an interrupted publication.
lock.mkdir()
try:
    with tempfile.TemporaryDirectory(prefix='runtime-stage-', dir=build) as tmp:
        staging = pathlib.Path(tmp)
        entry = pathlib.Path(os.environ.get('OPENCONNECT_BINARY', shutil.which('openconnect') or '/opt/homebrew/bin/openconnect')).resolve(strict=True)
        out = staging / 'BundledRuntime'
        out.mkdir()
        def run(args):
            return subprocess.check_output(list(map(str, args)), text=True, stderr=subprocess.PIPE)
        def deps(p):
            return list(dict.fromkeys(re.findall(r'^\s+(.+) \(compatibility version', run(['xcrun','otool','-arch','all','-L',p]), re.M)))
        graph, names, queue = {}, {}, [entry]
        while queue:
            src = queue.pop(0)
            if src in graph: continue
            name = 'openconnect' if src == entry else src.name
            if not re.fullmatch(r'[A-Za-z0-9_.+-]+', name): raise ValueError('Unsafe filename')
            if name in names and names[name] != src: raise ValueError('Dependency name collision')
            names[name] = src
            edges = {}
            ids = {line.strip() for line in run(['xcrun','otool','-D',src]).splitlines() if line.strip() and not line.endswith(':')}
            for dep in deps(src):
                if dep in ids: continue
                if dep.startswith(('/usr/lib/', '/System/Library/')): continue
                if not dep.startswith('/'): raise ValueError('Input dependencies must resolve to absolute paths')
                resolved = pathlib.Path(dep).resolve(strict=True)
                if resolved.name == 'libp11-kit.0.dylib':
                    resolved = isolated_p11
                edges[dep] = resolved
                if resolved != src: queue.append(resolved)
            graph[src] = (name, edges)
        architectures = set(run(['lipo','-archs',entry]).split())
        minimum = (0, 0, 0)
        for src in graph:
            versions = re.findall(r'minos ([0-9]+\.[0-9]+(?:\.[0-9]+)?)', run(['xcrun','vtool','-show-build',src]))
            if not versions: raise ValueError('Missing macOS minimum version')
            for version in versions:
                parts = tuple(map(int,version.split('.')))
                minimum = max(minimum, (parts+(0,0,0))[:3])
        for src, (name, edges) in graph.items():
            if not architectures.issubset(set(run(['lipo','-archs',src]).split())):
                raise ValueError('Dependency architecture mismatch')
            dst = out/name
            shutil.copyfile(src,dst); dst.chmod(0o755)
            args = ['xcrun','install_name_tool']
            if src != entry: args += ['-id','@loader_path/'+name]
            for old,dep in edges.items():
                if dep != src: args += ['-change',old,'@loader_path/'+graph[dep][0]]
            for rpath in dict.fromkeys(re.findall(r'cmd LC_RPATH\n\s*cmdsize \d+\n\s*path (.+) \(offset',run(['xcrun','otool','-l',dst]))):
                args += ['-delete_rpath',rpath]
            if len(args)>2: run(args+[dst])
            run(['codesign','--force','--sign','-','--timestamp=none',dst])
            for dep in deps(dst):
                if dep.startswith(('/usr/lib/','/System/Library/')): continue
                if not dep.startswith('@loader_path/') or dep.removeprefix('@loader_path/') not in names:
                    raise ValueError('Unclosed bundled dependency graph')
        script = root/'VPNMenuBar/Resources/vpnc-script--no-dns'
        shutil.copyfile(script,out/script.name); (out/script.name).chmod(0o755)
        expected = set(names)|{script.name}
        for p in out.iterdir():
            if p.name not in expected: raise ValueError('Unexpected stale runtime file: '+p.name)
        files = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.iterdir())}
        swift = '// Generated by scripts/prepare-bundled-runtime.py.\nimport Foundation\n\nenum BundledRuntimeFiles {\n    static let hashes: [String: String] = [\n'
        swift += ''.join('        '+json.dumps(k)+': '+json.dumps(v)+',\n' for k,v in files.items())
        swift += '    ]\n    static let architectures = '+json.dumps(sorted(architectures))+'\n'
        swift += '    static let minimumOS = OperatingSystemVersion(majorVersion: %d, minorVersion: %d, patchVersion: %d)\n}\n' % minimum
        (staging/'BundledRuntimeFiles.swift').write_text(swift)

        notices = staging/'ThirdParty'
        notices.mkdir(exist_ok=True)
        packages = set()
        for src in graph:
            for parent in src.parents:
                if (parent/'INSTALL_RECEIPT.json').is_file():
                    packages.add(parent); break
        for package in sorted(packages):
            target = notices/(package.parent.name+'-'+package.name)
            target.mkdir(exist_ok=True)
            for p in package.iterdir():
                if p.is_file() and (p.name.upper().startswith(('COPYING','LICENSE','AUTHORS')) or p.name == 'sbom.spdx.json'):
                    shutil.copyfile(p,target/p.name)
        (notices/'README.txt').write_text('Bundled OpenConnect and dependencies. Local build inventory; review license and corresponding-source requirements before external distribution.\n'+ '\n'.join(p.parent.name+' '+p.name for p in sorted(packages))+'\n')

        shutil.copyfile(root/'build/p11-isolated/p11-kit-0.26.5/COPYING', notices/'p11-kit-COPYING')
        backup = staging/'backup'; backup.mkdir()
        runtime_package.publish([
            (out, root/'VPNMenuBar/Resources/BundledRuntime'),
            (notices, root/'VPNMenuBar/Resources/ThirdParty'),
            (staging/'BundledRuntimeFiles.swift', root/'VPNMenuBar/Dependencies/BundledRuntimeFiles.swift')
        ], backup)
        print('Packaged',len(files),'files; architectures:',', '.join(sorted(architectures)))
finally:
    lock.rmdir()
